### ISSUE TITLE
Delta Green Need To Know 快速上手指南 不见了

### ISSUE THREAD

**Issue by XiaobinY** [DeltaGreenCHN/AgentsHandbook#1]
纯美苹果园的帖子里有一个github上快速上手指南的链接，但是链接失效了。是否可以把快速上手指南加进项目？

http://www.goddessfantasy.net/bbs/index.php?topic=126453.0
https://github.com/DeltaGreenCHN/Need-To-Know/releases/latest

**Comment by dkwingsmt** [comment]
已解决。感谢提醒。
